language: cpp

compiler:
 - clang
 - gcc

before_install:
 - sudo apt-add-repository --yes ppa:mapnik/v2.2.0
 - sudo apt-add-repository --yes ppa:mapnik/nightly-2.3
 - sudo apt-get update -qq

install:
 - sudo apt-get -qq install libprotobuf7 libprotobuf-dev protobuf-compiler

before_script:
 - sudo apt-get -qq install libmapnik=2.2.0* mapnik-utils=2.2.0* libmapnik-dev=2.2.0*
 - make clean
 - make test
 - sudo apt-get purge libmapnik=2.2.0* mapnik-utils=2.2.0* libmapnik-dev=2.2.0*

script:
 - sudo apt-get -qq install libmapnik=2.3.0* mapnik-utils=2.3.0* libmapnik-dev=2.3.0*
 - make clean
 - make test
 - sudo apt-get purge libmapnik=2.3.0* mapnik-utils=2.3.0* libmapnik-dev=2.3.0*

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
